---
- hosts: all
  become: true
  become_method: sudo
  user: root
  vars:
          remote_dir: /etc/ansible/facts.d
          facts_file: date_time.fact
  tasks:
          - name: get custom fact
            debug:
                    msg: "{{ ansible_local.date_time }}"
