---
- hosts: all
  become: yes
  user: netleap
  tasks:
          - name: postfix running
            service:
                    name: "{{item}}"
                    state: started
            loop:
                    - postfix
                    - dovecot

