---
- name: define variable according to diskname detected debug test
  hosts: all
  tasks:
  - ignore_errors: yes
    set_fact: 
      disk2name: sda
    when: ansible_facts['devices']['sda'] 
  - ignore_errors: yes
    set_fact:
      disk2name: sdb
    when: ansible_facts['devices']['sdb'] 
  - name: getting out if there is no second disk
    fail:
      msg: there is no second disk
    when: disk2name is not defined
  - name: showing this is only for hosts with a second disk
    debug:
      msg: continuing
