---
- hosts: all
  become: yes
  user: netleap
  vars:
          webserver_message: "i am running to the finish line"
  tasks:
          - name: install httpd
            yum:
                    name: httpd
                    state: present
          - name: start and enable httpd
            service:
                    name: httpd
                    state: started
                    enabled: true
          - name: create index.html using jinja2
            template:
                    src: index.j2
                    dest: /var/www/html/index.html
                    #notify: restart service
                    #handlers:
          - name: restart service
            service:
                    name: httpd
                    state: restarted  

